### ISSUE TITLE
_id property doesn't get saved

### ISSUE THREAD

**Issue by wormyy** [gagle/node-mongodb-fixture#1]
Hello

I created a fixture:

```
var fixture = {
    collection1: [
        {
            _id: '18L',
            url: 'https://someurl.eu'
        }
    ]
  };
```

but when I want to test, the _id prop is ommited:

```
mongodb.get('collection1', function (err, docs) {
      console.log(docs) // [{ "url": "https://someurl.eu"}]
    });
```

This library is exactly what I need, however this makes it unusable. Can you have look at this?

**Comment by gagle** [comment]
It's because the default projection is `{ _id: false }` but I can't remember why I took this decision, it doesn't have any sense. Tomorrow I'll change it.

**Comment by gagle** [comment]
done
